// ============================================
// SOULTAILS — STATIC FALLBACK DATA
// Used when Sanity CMS is not configured yet
// ============================================

export const STATIC_SERVICES = [
  {
    slug: "home-visit",
    name: "Home Visit Consultation",
    shortDescription: "Dr. Claudia comes to you — expert integrative veterinary care in the comfort of your home. Available 10am to 4pm in South East London and part of Kent.",
    fullDescription: [
      "Soultails brings a high quality veterinary service to the comfort of your home. We specifically wanted it to be targeted to your pet's needs and built it with their personality and desires in mind.",
      "This embraces a new fairer concept of contextualised veterinary care, with the pet and its family at the centre of it. In the familiar surroundings of home, your pet is more relaxed, which often leads to a more accurate assessment.",
      "Most visits last between 30 to 40 minutes, though it is best to allow up to an hour — as we work in cats and dogs' timings: at their own pace! We can give you a half hour arrival window.",
      "Payment is taken prior to appointments and exclusively via payment link. The receipt of payment is confirmation of the booked appointment.",
    ],
    icon: "Home",
    serviceMode: "home_visit",
    priceDisplay: "£130",
    duration: "30–60 minutes",
    whatToExpect: [
      "Half hour arrival window provided",
      "Full clinical assessment in your pet's familiar environment",
      "Physical examinations and treatments",
      "Integrative and conventional treatment recommendations",
      "Herbal medicine, essential oils, osteopathy and acupuncture as appropriate",
      "Secure payment link sent prior to appointment",
    ],
    metaDescription: "Vet home visit in South East London and Kent by Dr. Claudia Fioravanti DVM MRCVS. Expert integrative veterinary care at home. £130 per visit.",
  },
  {
    slug: "remote-consultation",
    name: "Remote Consultation (Zoom)",
    shortDescription: "Expert veterinary advice via secure Zoom video call — no travel stress for you or your pet. Up to 30 minutes.",
    fullDescription: [
      "Depending on your pet's condition, we are often able to offer remote appointments via Zoom meeting. These are ideal for follow-up appointments, second opinions, behaviour assessments, and non-emergency concerns.",
      "Before your appointment, you'll receive a secure Zoom link. Dr. Claudia will take the time to listen, observe your pet through video, and provide a thorough assessment combining conventional and integrative approaches.",
      "Remote follow-up appointments are also available at a reduced rate of £50.",
    ],
    icon: "Video",
    serviceMode: "remote",
    priceDisplay: "£90",
    duration: "Up to 30 minutes",
    whatToExpect: [
      "Secure Zoom video link sent to your email",
      "Thorough history taking and visual assessment",
      "Evidence-based recommendations combining conventional and integrative approaches",
      "Follow-up appointments available at £50",
      "Prescription referrals arranged with your local vet if needed",
    ],
    metaDescription: "Online veterinary consultation with Dr. Claudia Fioravanti DVM MRCVS. Expert integrative care via Zoom. £90 per session.",
  },
  {
    slug: "feline-behaviour",
    name: "Feline Behaviour Consultation",
    shortDescription: "Expert cat behaviour assessment by an ISFMAdvCerFB-certified professional. Requires a behaviour questionnaire completed in advance.",
    remotePrice: "£90",
    homeVisitPrice: "£130",
    fullDescription: [
      "Dr. Claudia Fioravanti holds the ISFM Advanced Certificate in Feline Behaviour — one of the highest qualifications available in this specialist field.",
      "Feline behaviour consultations can be particularly lengthy. We require you to fill in a behaviour questionnaire in advance and to allow us to study all the details of your concerns before the appointment.",
      "Cat behaviour concerns can range from house soiling and aggression to hiding, over-grooming, and anxiety. Dr. Claudia takes a holistic view, considering every aspect of your cat's life and environment.",
      "Available as both remote consultations and home visits. Home visits are particularly valuable for behaviour cases, as they allow observation in the cat's own environment.",
    ],
    icon: "Heart",
    serviceMode: "both",
    priceDisplay: "From £90",
    duration: "60–90 minutes",
    whatToExpect: [
      "Detailed behaviour questionnaire sent before appointment — please complete in full",
      "Full environmental and lifestyle assessment",
      "Expert analysis of triggers and underlying causes",
      "Personalised behaviour modification plan",
      "Ongoing support and follow-up available",
    ],
    metaDescription: "Cat behaviour expert consultation UK — Dr. Claudia Fioravanti ISFMAdvCerFB. Remote and home visit feline behaviour assessments.",
  },
  {
    slug: "chronic-pain-management",
    name: "Chronic Pain Management",
    shortDescription: "Integrative approach to assessing and managing chronic and acute pain — combining conventional medicine with acupuncture, osteopathy and more.",
    fullDescription: [
      "Chronic pain is one of the most under-recognised and under-treated conditions in companion animals. Dr. Claudia has specialist expertise in identifying and managing both chronic and acute pain using an integrative approach.",
      "Her approach combines thorough pain assessment with multimodal pain management strategies, which may include conventional analgesics alongside complementary therapies such as acupuncture, osteopathy, massage therapies, herbal medicine, and nutritional support.",
      "Monthly consultations are often needed for certain pain relief modalities to maintain effectiveness and adjust the treatment plan as your pet's needs evolve.",
    ],
    icon: "Activity",
    serviceMode: "both",
    priceDisplay: "From £90",
    remotePrice: "£90",
    homeVisitPrice: "£130",
    duration: "45–60 minutes",
    whatToExpect: [
      "Comprehensive pain scoring and assessment",
      "Multimodal pain management plan tailored to your pet",
      "Integration of conventional and complementary approaches",
      "Acupuncture, osteopathy and massage as appropriate",
      "Ongoing monitoring — monthly consultations often recommended",
    ],
    metaDescription: "Chronic pain management for pets by Dr. Claudia Fioravanti DVM MRCVS. Integrative approach combining conventional and complementary therapies.",
  },
  {
    slug: "puppy-kitten-consultations",
    name: "Puppy & Kitten Consultations",
    shortDescription: "Give your new companion the best possible start — preventative care, nutrition guidance and health checks tailored to puppies and kittens.",
    fullDescription: [
      "The early months of a puppy or kitten's life are crucial for their long-term health and wellbeing. Dr. Claudia offers integrative new pet consultations that go beyond the standard health check.",
      "We cover vaccination protocols, parasite prevention, nutrition and diet planning, socialisation guidance, and early behaviour foundations — all tailored to your pet's individual needs and lifestyle.",
      "Starting with the right foundations sets your pet up for a lifetime of good health.",
    ],
    icon: "Star",
    serviceMode: "both",
    priceDisplay: "From £90",
    remotePrice: "£90",
    homeVisitPrice: "£130",
    duration: "45–60 minutes",
    whatToExpect: [
      "Full health assessment appropriate to age",
      "Vaccination and parasite prevention guidance",
      "Tailored nutrition and diet recommendations",
      "Socialisation and early behaviour advice",
      "Preventative care plan for the months ahead",
    ],
    metaDescription: "Puppy and kitten consultations by Dr. Claudia Fioravanti DVM MRCVS. Integrative new pet health checks in South East London and online.",
  },
  {
    slug: "acupuncture-osteopathy",
    name: "Acupuncture & Osteopathy",
    shortDescription: "Evidence-based complementary therapies including acupuncture, osteopathy and massage — used alongside conventional medicine for whole-animal wellbeing.",
    fullDescription: [
      "Dr. Claudia integrates acupuncture, osteopathy and massage therapies into her veterinary practice as evidence-based tools to support healing and improve quality of life.",
      "Acupuncture can be particularly effective for pain management, musculoskeletal conditions, neurological support, and post-operative recovery. Osteopathy and massage therapies help restore mobility and reduce tension.",
      "These therapies are always used alongside — never instead of — conventional veterinary medicine, as part of a comprehensive, individualised treatment plan.",
    ],
    icon: "Leaf",
    serviceMode: "home_visit",
    priceDisplay: "£130",
    duration: "30–60 minutes",
    whatToExpect: [
      "Assessment to determine suitability for complementary therapies",
      "Acupuncture using sterile single-use needles",
      "Osteopathy and massage as appropriate",
      "Integration with your pet's existing treatment plan",
      "Regular sessions often recommended for best results",
    ],
    metaDescription: "Veterinary acupuncture and osteopathy for pets by Dr. Claudia Fioravanti DVM MRCVS. Home visits in South East London and Kent.",
  },
  {
    slug: "nutrition-integrative",
    name: "Nutrition & Herbal Medicine",
    shortDescription: "Personalised nutrition plans, herbal medicine, essential oils and supplements — evidence-based integrative care for whole-animal health.",
    fullDescription: [
      "Nutrition is the foundation of health, yet it is often overlooked in conventional veterinary practice. Dr. Claudia takes a deep dive into your pet's diet and nutritional status, identifying deficiencies or imbalances that may be contributing to health issues.",
      "Her integrative approach also encompasses herbal medicine, essential oils treatment, and nutraceuticals — all selected based on current evidence and your pet's individual needs.",
      "Monthly consultations are often needed for nutrition health checks to monitor progress and adjust recommendations as your pet's condition evolves.",
    ],
    icon: "Leaf",
    serviceMode: "both",
    priceDisplay: "From £90",
    remotePrice: "£90",
    homeVisitPrice: "£130",
    duration: "45–60 minutes",
    whatToExpect: [
      "Detailed dietary history and nutritional assessment",
      "Personalised nutrition plan tailored to your pet",
      "Herbal medicine and supplement recommendations",
      "Essential oils guidance where appropriate",
      "Monthly check-ins available for ongoing conditions",
    ],
    metaDescription: "Pet nutrition and herbal medicine by Dr. Claudia Fioravanti DVM MRCVS. Integrative approach for cats and dogs in South East London and online.",
  },
  {
    slug: "palliative-care",
    name: "Palliative & Senior Pet Care",
    shortDescription: "Compassionate, dignified care for elderly and end-of-life pets — focusing on comfort, quality of life and support for the whole family.",
    fullDescription: [
      "When a beloved pet reaches the end of their life, the focus shifts to comfort, dignity, and quality of life. Dr. Claudia provides compassionate palliative care that supports both the animal and the entire family through this difficult time.",
      "For senior pets, Dr. Claudia offers comprehensive health assessments that take a whole-body approach — considering physical signs of ageing, cognitive function, emotional wellbeing, and environmental factors.",
      "Preventative care is also tailored depending on your pet's age and lifestyle, helping to maintain quality of life for as long as possible.",
    ],
    icon: "Heart",
    serviceMode: "both",
    priceDisplay: "Contact for pricing",
    remotePrice: "£90",
    homeVisitPrice: "£130",
    duration: "As needed",
    whatToExpect: [
      "Compassionate, unhurried assessment",
      "Personalised comfort and senior care plan",
      "Pain and symptom management",
      "Preventative care tailored to age and lifestyle",
      "Honest, sensitive guidance on quality of life",
    ],
    metaDescription: "Palliative and senior pet care by Dr. Claudia Fioravanti DVM MRCVS. Compassionate home visit service in South East London and Kent.",
  },
]

export const STATIC_POSTS = [
  {
    slug: "signs-your-cat-is-in-pain",
    title: "5 Signs Your Cat May Be in Chronic Pain",
    excerpt: "Cats are masters at hiding discomfort. Learn the subtle behavioural and physical signs that may indicate your cat is experiencing chronic pain — and what to do about it.",
    category: "pain-management",
    publishedAt: "2024-03-15",
    body: [],
    featured: true,
  },
  {
    slug: "integrative-vs-conventional-vet",
    title: "What is Integrative Veterinary Medicine?",
    excerpt: "Integrative veterinary medicine combines the best of conventional evidence-based medicine with carefully selected complementary therapies. Here's what that means in practice.",
    category: "general",
    publishedAt: "2024-02-28",
    body: [],
    featured: true,
  },
  {
    slug: "cat-behaviour-home-environment",
    title: "How Your Home Environment Affects Your Cat's Behaviour",
    excerpt: "Indoor cats rely entirely on us to meet their behavioural needs. Small changes to the home environment can have a profound impact on feline wellbeing and behaviour.",
    category: "feline-behaviour",
    publishedAt: "2024-01-20",
    body: [],
    featured: false,
  },
]

export const SITE_SETTINGS = {
  doctorName: "Dr. Claudia Fioravanti",
  tagline: "Bringing high quality veterinary care to the comfort of your home",
  credentials: ["DVM", "MRCVS", "CertAVP", "ISFMAdvCerFB"],
  email: "soultailsinfo@gmail.com",
  serviceArea: "South East London & part of Kent",
}
