// ============================================
// SOULTAILS — STATIC FALLBACK DATA
// Used when Sanity CMS is not configured yet
// Replace with real Sanity data later
// ============================================

export const STATIC_SERVICES = [
  {
    slug: "remote-consultation",
    name: "Remote Consultation",
    shortDescription: "Expert veterinary advice via secure video call — no travel stress for you or your pet.",
    fullDescription: [
      "Connect with Dr. Claudia Fioravanti from the comfort of your own home via a secure Zoom video call. Remote consultations are ideal for follow-up appointments, second opinions, behaviour assessments, and non-emergency concerns.",
      "Before your appointment, you'll receive a confirmation email with your secure Zoom link and guidance on how to prepare. Dr. Claudia will take the time to listen, observe your pet through video, and provide a thorough assessment.",
      "Following your consultation, you'll receive a written summary of recommendations and any suggested next steps — all at a fraction of the cost and stress of a traditional clinic visit.",
    ],
    icon: "Video",
    serviceMode: "remote",
    priceDisplay: "From £80",
    duration: "45–60 minutes",
    whatToExpect: [
      "Secure Zoom video link sent to your email",
      "Thorough history taking and visual assessment",
      "Evidence-based recommendations combining conventional and integrative approaches",
      "Written follow-up summary emailed after the consultation",
      "Prescription referrals arranged with your local vet if needed",
    ],
    metaDescription: "Online veterinary consultation with Dr. Claudia Fioravanti DVM MRCVS. Expert integrative care from home via secure video call. Book today.",
  },
  {
    slug: "home-visit-vet",
    name: "Home Visits",
    shortDescription: "Dr. Claudia comes to you — perfect for anxious animals or owners with limited mobility.",
    fullDescription: [
      "A home visit from Dr. Claudia Fioravanti brings expert integrative veterinary care directly to your doorstep. This service is ideal for pets who experience significant stress when travelling, elderly animals, or owners with limited mobility.",
      "In the familiar comfort of your home, your pet is more relaxed, which often leads to a more accurate assessment and a more thorough consultation. Dr. Claudia will take her time with you and your pet, never rushing the appointment.",
      "Home visits are available in London and surrounding areas. Payment is arranged after the visit via a secure payment link.",
    ],
    icon: "Home",
    serviceMode: "home_visit",
    priceDisplay: "From £120",
    duration: "60–90 minutes",
    whatToExpect: [
      "Dr. Claudia visits your home at the agreed time",
      "Full clinical assessment in your pet's familiar environment",
      "Integrative and conventional treatment recommendations",
      "Written summary and care plan provided after the visit",
      "Secure payment link sent by email after the consultation",
    ],
    metaDescription: "Vet home visit service in London by Dr. Claudia Fioravanti DVM MRCVS. Expert integrative veterinary care in your home. Book today.",
  },
  {
    slug: "feline-behaviour",
    name: "Feline Behaviour",
    shortDescription: "Expert cat behaviour assessment and management plans by an ISFMAdvCerFB-certified professional.",
    fullDescription: [
      "Dr. Claudia Fioravanti holds the ISFM Advanced Certificate in Feline Behaviour — one of the highest qualifications available in this specialist field. She brings this expert knowledge to every feline behaviour consultation.",
      "Cat behaviour concerns can range from house soiling and aggression to hiding, over-grooming, and anxiety. These behaviours are often signs of underlying stress, medical issues, or environmental factors. Dr. Claudia takes a holistic view, considering every aspect of your cat's life.",
      "Available as both remote consultations and home visits. Home visits are particularly valuable for behaviour cases, as they allow Dr. Claudia to observe your cat in their own environment and identify environmental triggers.",
    ],
    icon: "Cat",
    serviceMode: "both",
    priceDisplay: "From £90",
    duration: "60–75 minutes",
    whatToExpect: [
      "Detailed behavioural history questionnaire sent before the appointment",
      "Full environmental and lifestyle assessment",
      "Expert analysis of triggers and underlying causes",
      "Personalised behaviour modification plan",
      "Ongoing support and follow-up available",
    ],
    metaDescription: "Cat behaviour expert consultation UK — Dr. Claudia Fioravanti ISFMAdvCerFB. Remote and home visit feline behaviour assessments. Book today.",
  },
  {
    slug: "chronic-pain-management",
    name: "Chronic Pain Management",
    shortDescription: "Integrative approach to assessing and managing chronic pain in pets — combining conventional and complementary therapies.",
    fullDescription: [
      "Chronic pain is one of the most under-recognised and under-treated conditions in companion animals. Dr. Claudia Fioravanti has specialist expertise in identifying and managing chronic pain using an integrative approach that goes beyond conventional medication.",
      "Her approach combines thorough pain assessment with multimodal pain management strategies, which may include conventional analgesics alongside complementary therapies such as acupuncture, physiotherapy referrals, environmental modifications, and nutritional support.",
      "This service is available as a home visit (preferred for pain assessment) or remote consultation for follow-up appointments and monitoring.",
    ],
    icon: "Activity",
    serviceMode: "both",
    priceDisplay: "From £110",
    duration: "60–90 minutes",
    whatToExpect: [
      "Comprehensive pain scoring and assessment",
      "Multimodal pain management plan tailored to your pet",
      "Integration of conventional and complementary approaches",
      "Referrals to physiotherapists or other specialists as needed",
      "Ongoing monitoring and plan adjustment",
    ],
    metaDescription: "Chronic pain management for pets by Dr. Claudia Fioravanti DVM MRCVS. Integrative approach combining conventional and complementary therapies.",
  },
  {
    slug: "palliative-care",
    name: "Palliative Care",
    shortDescription: "Compassionate, dignified end-of-life care that focuses on comfort, quality of life and family support.",
    fullDescription: [
      "When a beloved pet reaches the end of their life, the focus shifts to comfort, dignity, and quality of life. Dr. Claudia Fioravanti provides compassionate palliative care that supports both the animal and the entire family through this difficult time.",
      "Palliative care aims to minimise suffering, manage symptoms, and maximise the quality of the time remaining. Dr. Claudia will work with you to develop a personalised comfort plan and help you understand and recognise signs of pain or distress.",
      "This service is primarily provided as a home visit, allowing your pet to remain in the comfort and safety of their own environment. Dr. Claudia also provides ongoing emotional support and guidance to help families through the grieving process.",
    ],
    icon: "Heart",
    serviceMode: "home_visit",
    priceDisplay: "Contact for pricing",
    duration: "As needed",
    whatToExpect: [
      "Compassionate, unhurried assessment in your home",
      "Personalised comfort care plan",
      "Pain and symptom management",
      "Honest, sensitive guidance on quality of life",
      "Emotional support for the whole family",
    ],
    metaDescription: "Palliative and end-of-life care for pets by Dr. Claudia Fioravanti DVM MRCVS. Compassionate home visit service in London and surrounding areas.",
  },
  {
    slug: "senior-pet-care",
    name: "Senior Pet Care",
    shortDescription: "Tailored health assessments and holistic management plans for elderly pets addressing age-related conditions.",
    fullDescription: [
      "As pets age, their health needs become more complex. Senior animals are more prone to arthritis, cognitive decline, organ dysfunction, and sensory changes — many of which can significantly impact their quality of life if left unaddressed.",
      "Dr. Claudia Fioravanti offers comprehensive senior pet health assessments that take a whole-body approach. She considers not only the physical signs of ageing but also cognitive function, emotional wellbeing, and environmental factors.",
      "Her integrative approach means she can offer a wide range of management options — from conventional medication to nutritional support, environmental enrichment, and complementary therapies — to help your senior pet live their best life.",
    ],
    icon: "Star",
    serviceMode: "both",
    priceDisplay: "From £90",
    duration: "60–75 minutes",
    whatToExpect: [
      "Thorough senior health assessment",
      "Cognitive function and mobility evaluation",
      "Personalised age-appropriate management plan",
      "Nutritional and environmental recommendations",
      "Ongoing monitoring and support",
    ],
    metaDescription: "Senior pet care expert UK — Dr. Claudia Fioravanti DVM MRCVS. Holistic health assessments and management plans for elderly cats and dogs.",
  },
  {
    slug: "nutrition-integrative",
    name: "Nutrition & Integrative Care",
    shortDescription: "Personalised nutrition plans and integrative care incorporating evidence-based complementary approaches.",
    fullDescription: [
      "Nutrition is the foundation of health, yet it is often overlooked in conventional veterinary practice. Dr. Claudia Fioravanti takes a deep dive into your pet's diet and nutritional status, identifying deficiencies or imbalances that may be contributing to health issues.",
      "Her integrative approach also encompasses a range of evidence-based complementary therapies, which may include acupuncture, herbal medicine, nutraceuticals, and lifestyle modifications. All recommendations are grounded in current scientific research.",
      "This service is available remotely and is ideal for pets with chronic conditions, food sensitivities, weight issues, or owners who simply want to optimise their pet's health through diet and lifestyle.",
    ],
    icon: "Leaf",
    serviceMode: "remote",
    priceDisplay: "From £80",
    duration: "45–60 minutes",
    whatToExpect: [
      "Detailed dietary history and nutritional assessment",
      "Personalised nutrition plan tailored to your pet's needs",
      "Evidence-based complementary therapy recommendations",
      "Supplement and nutraceutical guidance",
      "Written plan provided after the consultation",
    ],
    metaDescription: "Pet nutrition and integrative veterinary care by Dr. Claudia Fioravanti DVM MRCVS. Evidence-based holistic approach for cats and dogs UK.",
  },
]

export const STATIC_POSTS = [
  {
    slug: "signs-your-cat-is-in-pain",
    title: "5 Signs Your Cat May Be in Chronic Pain",
    excerpt: "Cats are masters at hiding discomfort. Learn the subtle behavioural and physical signs that may indicate your cat is experiencing chronic pain — and what to do about it.",
    category: "pain-management",
    publishedAt: "2024-03-15",
    body: [
      "Cats have evolved to hide signs of pain and vulnerability — a survival instinct from their days as both predator and prey in the wild. This means that by the time a cat's pain becomes obvious, it has often been present for some time.",
      "As a veterinarian with specialist expertise in chronic pain management, I see cats regularly whose owners had no idea their pet was suffering. Here are five key signs to watch for.",
      "1. Changes in grooming habits. A cat in pain may groom less overall, leading to a dull or matted coat — or may over-groom a specific area, causing hair loss or skin irritation over a painful spot.",
      "2. Altered movement and posture. Watch for reluctance to jump, difficulty climbing stairs, stiffness when getting up, or changes in how your cat holds their body. These are classic signs of musculoskeletal pain.",
      "3. Changes in behaviour and temperament. A normally sociable cat becoming withdrawn, or a calm cat becoming irritable or even aggressive, can indicate pain. Any significant personality change warrants investigation.",
      "4. Reduced appetite and activity. Pain is exhausting. A cat experiencing chronic discomfort may eat less, sleep more, and lose interest in play and interaction.",
      "5. Changes in litter box use. Pain can make it difficult to adopt the posture required to use a litter box, particularly for cats with arthritis or back pain.",
      "If you notice any of these signs in your cat, I would encourage you to seek veterinary advice promptly. Pain is not an inevitable part of ageing — there is a great deal that can be done to improve quality of life.",
    ],
    featured: true,
  },
  {
    slug: "integrative-vs-conventional-vet",
    title: "What is Integrative Veterinary Medicine?",
    excerpt: "Integrative veterinary medicine combines the best of conventional evidence-based medicine with carefully selected complementary therapies. Here's what that means in practice.",
    category: "general",
    publishedAt: "2024-02-28",
    body: [
      "The term 'integrative medicine' sometimes raises eyebrows. Does it mean abandoning conventional medicine for alternative approaches? Absolutely not. Integrative veterinary medicine means using the full range of available evidence-based treatments — both conventional and complementary — to achieve the best possible outcome for the patient.",
      "As a conventionally trained veterinary surgeon (DVM MRCVS CertAVP), I hold science and evidence at the core of everything I do. I do not recommend any therapy without a solid evidence base or a clear rationale for its use.",
      "What integrative medicine adds is breadth. For a cat with chronic arthritis, for example, conventional pain management (NSAIDs, gabapentin) may be effective but incomplete. Adding acupuncture, targeted physiotherapy, environmental modifications, and nutritional support can significantly improve outcomes and quality of life.",
      "The key principle is that treatments are selected for the individual patient based on evidence and clinical judgement — not based on ideology. Some patients respond beautifully to acupuncture; others do not. The integrative approach means we have more tools available.",
      "If you have questions about whether integrative medicine might benefit your pet, I am always happy to discuss. A remote consultation is a great place to start.",
    ],
    featured: true,
  },
  {
    slug: "cat-behaviour-home-environment",
    title: "How Your Home Environment Affects Your Cat's Behaviour",
    excerpt: "Indoor cats rely entirely on us to meet their behavioural needs. Small changes to the home environment can have a profound impact on feline wellbeing and behaviour.",
    category: "feline-behaviour",
    publishedAt: "2024-01-20",
    body: [
      "Cats are territorial, largely solitary hunters who communicate primarily through scent. The modern domestic cat — particularly the indoor cat — lives in an environment that is often at odds with these fundamental needs. Understanding this can transform how we care for our feline companions.",
      "The five pillars of a healthy feline environment, as defined by the International Society of Feline Medicine (ISFM), provide a useful framework. These are: a safe place to retreat to; multiple and separated key resources (food, water, litter, resting spots); opportunities for play and predatory behaviour; positive and consistent human interaction; and respect for the cat's sensory world.",
      "Common environmental issues I see in feline behaviour consultations include: insufficient vertical space and hiding spots, litter trays that are too few, too small, or poorly positioned, resources that are placed too close together (forcing confrontation in multi-cat households), and lack of opportunities for hunting-like play.",
      "The good news is that many behaviour problems can be significantly improved with relatively simple environmental changes — no medication required. If your cat is showing any concerning behaviours, a feline behaviour consultation can help identify the root cause and develop a practical plan.",
    ],
    featured: false,
  },
]

export const SITE_SETTINGS = {
  doctorName: "Dr. Claudia Fioravanti",
  tagline: "Integrative veterinary care for the whole animal",
  credentials: ["DVM", "MRCVS", "CertAVP", "ISFMAdvCerFB"],
  email: "hello@soultails.com",
  serviceArea: "London & surrounding areas",
}
