const block = (key, text) => ({
  _type: 'block',
  _key: key,
  style: 'normal',
  markDefs: [],
  children: [{ _type: 'span', _key: `${key}s`, text }],
})

export const services = [
  {
    _type: 'service',
    _id: 'service-home-visit',
    name: 'Home Visit Consultation',
    slug: { _type: 'slug', current: 'home-visit' },
    shortDescription:
      "Dr. Claudia comes to you - expert integrative veterinary care in the comfort of your home. Available 10am to 4pm in South East London and parts of Kent.",
    fullDescription: [
      block('hv1', "Soultails brings high-quality veterinary care into your home, shaped around your pet's individual needs, pace and personality."),
      block('hv2', 'This allows veterinary care to happen in a more familiar setting, where many pets feel calmer and can be assessed more accurately.'),
      block('hv3', "Most visits last 30 to 40 minutes, though it is best to allow up to an hour so your pet can be seen without rushing."),
      block('hv4', "Appointments are confirmed after Dr. Claudia reviews your enquiry, confirms availability and sends a secure PayPal payment link."),
    ],
    icon: 'Home',
    serviceMode: 'home_visit',
    priceDisplay: '£130',
    duration: '30-60 minutes',
    whatToExpect: [
      'A half-hour arrival window before the visit',
      "A full clinical assessment in your pet's familiar environment",
      'Physical examination and treatment where appropriate',
      'Integrative and conventional treatment recommendations',
      'Secure payment link sent after booking confirmation',
    ],
    order: 1,
    featured: true,
    metaDescription:
      'Home visit vet in South East London and Kent by Dr. Claudia Fioravanti DVM MRCVS. Integrative veterinary care for pets in the comfort of home.',
    bestFor:
      'Best for pets who feel stressed at clinics, need a hands-on assessment, have mobility issues, or benefit from calm home-based care.',
    availability: 'South East London and parts of Kent',
    serviceAreaLabel: 'Home visit',
    ctaLabel: 'Request home visit',
    pricingNote:
      "Pricing depends on your pet's needs and location. Send an enquiry and Dr. Claudia will confirm the best option within 24 hours.",
    hidePublicPricing: true,
  },
  {
    _type: 'service',
    _id: 'service-remote-consultation',
    name: 'Remote Consultation',
    slug: { _type: 'slug', current: 'remote-consultation' },
    shortDescription:
      'Expert veterinary advice by secure Zoom call - ideal for second opinions, follow-ups, behaviour support, nutrition guidance and non-emergency concerns across the UK.',
    fullDescription: [
      block('rc1', "Depending on your pet's condition, remote consultations may be the best way to get timely guidance without the stress of travel."),
      block('rc2', "Before your appointment, you'll receive a secure Zoom link. Dr. Claudia will take time to listen, observe your pet where possible and provide a considered assessment."),
      block('rc3', 'Remote follow-up appointments are also available when ongoing support is needed.'),
    ],
    icon: 'Video',
    serviceMode: 'remote',
    priceDisplay: 'From £90',
    remotePrice: '£90',
    duration: 'Up to 30 minutes',
    whatToExpect: [
      'Secure Zoom link sent by email after confirmation',
      'Thorough history-taking and visual assessment',
      'Recommendations that combine conventional and integrative approaches',
      'Follow-up appointments available when needed',
      'Prescription referrals coordinated with your local vet if appropriate',
    ],
    order: 2,
    featured: true,
    metaDescription:
      'Remote vet consultation across the UK with Dr. Claudia Fioravanti DVM MRCVS. Integrative veterinary advice by Zoom.',
    bestFor:
      'Best for general advice, second opinions, follow-ups, nutrition support, behaviour concerns and non-emergency guidance.',
    availability: 'Across the UK via Zoom',
    serviceAreaLabel: 'Remote consultation',
    ctaLabel: 'Book remote consultation',
    pricingNote: "Remote consultation pricing is confirmed after enquiry and based on the support your pet needs.",
    hidePublicPricing: true,
  },
  {
    _type: 'service',
    _id: 'service-feline-behaviour',
    name: 'Feline Behaviour Consultation',
    slug: { _type: 'slug', current: 'feline-behaviour' },
    shortDescription:
      'Specialist cat behaviour support for anxiety, conflict, house soiling, over-grooming and environmental stress. Available remotely across the UK or as a home visit in South East London and parts of Kent.',
    fullDescription: [
      block('fb1', 'Dr. Claudia Fioravanti holds the ISFM Advanced Certificate in Feline Behaviour, a specialist qualification in this field.'),
      block('fb2', 'Before the consultation, you will complete a behaviour questionnaire so the background and context can be reviewed in detail.'),
      block('fb3', 'Behaviour concerns can involve the home environment, medical factors, routine, social tension and unmet behavioural needs. Each case is approached holistically.'),
      block('fb4', "Home visits can be especially valuable for behaviour cases because they allow the cat's environment to be considered directly."),
    ],
    icon: 'Heart',
    serviceMode: 'both',
    priceDisplay: 'From £90',
    remotePrice: '£90',
    homeVisitPrice: '£130',
    duration: '60-90 minutes',
    whatToExpect: [
      'Detailed behaviour questionnaire before the appointment',
      'Full environmental and lifestyle assessment',
      'Clear review of triggers and possible underlying causes',
      'Personalised behaviour support plan',
      'Follow-up support where needed',
    ],
    order: 3,
    featured: true,
    metaDescription:
      'Feline behaviour consultation UK with Dr. Claudia Fioravanti ISFMAdvCerFB. Remote and home visit support for cat behaviour concerns.',
    bestFor:
      'Best for house soiling, anxiety, aggression, over-grooming, conflict between cats and other behaviour concerns.',
    availability: 'Remote across the UK or home visits in South East London and parts of Kent',
    serviceAreaLabel: 'Remote or home visit',
    ctaLabel: 'Book feline behaviour consultation',
    pricingNote:
      'Behaviour cases vary in complexity. A questionnaire is reviewed before the appointment and final pricing is confirmed after enquiry.',
    hidePublicPricing: true,
  },
  {
    _type: 'service',
    _id: 'service-chronic-pain',
    name: 'Chronic Pain Management',
    slug: { _type: 'slug', current: 'chronic-pain-management' },
    shortDescription:
      'Integrative support for arthritis, mobility issues and long-term pain - combining conventional veterinary medicine with therapies such as acupuncture, osteopathy and rehabilitation guidance.',
    fullDescription: [
      block('cp1', 'Chronic pain is often under-recognised in pets, especially when symptoms build gradually over time.'),
      block('cp2', 'Dr. Claudia uses a multimodal approach that may include pain scoring, medication review, lifestyle advice, acupuncture, osteopathy, massage, herbal support and nutrition guidance.'),
      block('cp3', "Ongoing reviews are often useful so the plan can evolve with your pet's comfort, mobility and quality of life."),
    ],
    icon: 'Activity',
    serviceMode: 'both',
    priceDisplay: 'From £90',
    remotePrice: '£90',
    homeVisitPrice: '£130',
    duration: '45-60 minutes',
    whatToExpect: [
      'Comprehensive pain and mobility assessment',
      'Tailored multimodal pain management plan',
      'Integration of conventional and complementary approaches',
      'Hands-on therapies where appropriate for home visits',
      'Ongoing monitoring and reassessment',
    ],
    order: 4,
    featured: true,
    metaDescription:
      'Chronic pain management for dogs and cats by Dr. Claudia Fioravanti DVM MRCVS. Integrative support for mobility and comfort.',
    bestFor:
      'Best for arthritis, mobility changes, long-term pain, comfort care, recovery support and senior pets needing ongoing management.',
    availability: 'Remote across the UK or home visits in South East London and parts of Kent',
    serviceAreaLabel: 'Remote or home visit',
    ctaLabel: 'Get chronic pain support',
    pricingNote:
      'Pricing depends on whether your pet needs remote guidance or hands-on support. Final cost is confirmed after enquiry.',
    hidePublicPricing: true,
  },
  {
    _type: 'service',
    _id: 'service-puppy-kitten',
    name: 'Puppy & Kitten Consultations',
    slug: { _type: 'slug', current: 'puppy-kitten-consultations' },
    shortDescription:
      'Preventative care, nutrition guidance and early-life support to help puppies and kittens get the healthiest possible start.',
    fullDescription: [
      block('pk1', "The first months of a puppy or kitten's life shape their long-term health and wellbeing."),
      block('pk2', 'These consultations go beyond a basic health check and cover feeding, parasite prevention, vaccination discussions, socialisation and early behaviour foundations.'),
      block('pk3', 'Recommendations are tailored to your pet, their breed, their home environment and your goals as a family.'),
    ],
    icon: 'Star',
    serviceMode: 'both',
    priceDisplay: 'From £90',
    remotePrice: '£90',
    homeVisitPrice: '£130',
    duration: '45-60 minutes',
    whatToExpect: [
      'Age-appropriate health assessment',
      'Nutrition and feeding guidance',
      'Vaccination and parasite prevention discussion',
      'Socialisation and behaviour foundations',
      'Preventative care plan for the months ahead',
    ],
    order: 5,
    featured: false,
    metaDescription:
      'Puppy and kitten consultations with Dr. Claudia Fioravanti DVM MRCVS. Integrative preventative care in London and online.',
    bestFor:
      'Best for new puppies and kittens who need preventative care, feeding guidance, behaviour foundations and a healthy start.',
    availability: 'Remote across the UK or home visits in South East London and parts of Kent',
    serviceAreaLabel: 'Remote or home visit',
    ctaLabel: 'Book puppy or kitten consultation',
    pricingNote: 'Pricing is confirmed after enquiry based on whether you need remote guidance or a home visit.',
    hidePublicPricing: true,
  },
  {
    _type: 'service',
    _id: 'service-acupuncture',
    name: 'Acupuncture & Osteopathy',
    slug: { _type: 'slug', current: 'acupuncture-osteopathy' },
    shortDescription:
      'Evidence-based complementary therapies that support pain relief, mobility and recovery, used alongside conventional veterinary treatment.',
    fullDescription: [
      block('ao1', 'Acupuncture, osteopathy and massage can play a valuable role in integrative care when chosen for the right patient and condition.'),
      block('ao2', 'These therapies are used to support comfort, mobility, healing and quality of life as part of a wider treatment plan.'),
      block('ao3', 'They are always integrated with conventional veterinary medicine rather than used as a substitute for it.'),
    ],
    icon: 'Leaf',
    serviceMode: 'home_visit',
    priceDisplay: '£130',
    duration: '30-60 minutes',
    whatToExpect: [
      'Assessment to decide whether treatment is appropriate',
      'Acupuncture using sterile single-use needles where suitable',
      'Osteopathy and massage when appropriate',
      "Integration with your pet's wider treatment plan",
      'Regular sessions recommended where ongoing support is beneficial',
    ],
    order: 6,
    featured: false,
    metaDescription:
      'Veterinary acupuncture and osteopathy for pets in South East London and Kent by Dr. Claudia Fioravanti DVM MRCVS.',
    bestFor:
      'Best for pain management, mobility support, musculoskeletal issues, recovery care and pets who may benefit from integrative physical therapies.',
    availability: 'South East London and parts of Kent',
    serviceAreaLabel: 'Home visit',
    ctaLabel: 'Request acupuncture or osteopathy',
    pricingNote: "Treatment plans are tailored to your pet. Final pricing is confirmed after enquiry.",
    hidePublicPricing: true,
  },
  {
    _type: 'service',
    _id: 'service-nutrition',
    name: 'Nutrition & Herbal Medicine',
    slug: { _type: 'slug', current: 'nutrition-integrative' },
    shortDescription:
      'Personalised nutrition plans, supplement support and herbal medicine recommendations as part of evidence-based integrative care.',
    fullDescription: [
      block('nh1', 'Nutrition is a core part of whole-animal health and can influence energy, digestion, skin, weight, recovery and long-term wellbeing.'),
      block('nh2', 'Dr. Claudia reviews diet, routine, medical history and current concerns to build a practical plan for your pet.'),
      block('nh3', 'Where appropriate, herbal medicine, nutraceuticals and other integrative options may be included alongside conventional care.'),
    ],
    icon: 'Leaf',
    serviceMode: 'both',
    priceDisplay: 'From £90',
    remotePrice: '£90',
    homeVisitPrice: '£130',
    duration: '45-60 minutes',
    whatToExpect: [
      'Detailed dietary history and nutritional assessment',
      'Personalised recommendations tailored to your pet',
      'Supplement and herbal medicine guidance where appropriate',
      'Practical steps you can follow at home',
      'Review appointments for ongoing conditions if needed',
    ],
    order: 7,
    featured: false,
    metaDescription:
      'Pet nutrition and herbal medicine support by Dr. Claudia Fioravanti DVM MRCVS. Integrative guidance for cats and dogs in London and across the UK online.',
    bestFor:
      'Best for diet reviews, chronic conditions, gut and skin issues, herbal support, supplements and integrative health planning.',
    availability: 'Remote across the UK or home visits in South East London and parts of Kent',
    serviceAreaLabel: 'Remote or home visit',
    ctaLabel: 'Book nutrition support',
    pricingNote: 'Pricing depends on the depth of review your pet needs and is confirmed after enquiry.',
    hidePublicPricing: true,
  },
  {
    _type: 'service',
    _id: 'service-palliative',
    name: 'Palliative & Senior Pet Care',
    slug: { _type: 'slug', current: 'palliative-care' },
    shortDescription:
      'Compassionate, unhurried support for senior pets and end-of-life care, focused on comfort, dignity and quality of life.',
    fullDescription: [
      block('ps1', 'As pets age or enter advanced illness, care often needs to become more tailored, gentle and practical.'),
      block('ps2', 'Dr. Claudia supports families with comfort-focused care, symptom management, quality-of-life discussions and planning for the next steps.'),
      block('ps3', 'Senior pet consultations also help review mobility, cognition, behaviour, environment and routine so life can remain as comfortable and meaningful as possible.'),
    ],
    icon: 'Heart',
    serviceMode: 'both',
    priceDisplay: 'Pricing confirmed after enquiry',
    remotePrice: '£90',
    homeVisitPrice: '£130',
    duration: 'As needed',
    whatToExpect: [
      'Compassionate assessment without rushing',
      'Personalised comfort and senior care planning',
      'Pain and symptom management guidance',
      'Support with quality-of-life decisions',
      'Sensitive family guidance and follow-up where needed',
    ],
    order: 8,
    featured: false,
    metaDescription:
      'Palliative and senior pet care with Dr. Claudia Fioravanti DVM MRCVS. Compassionate integrative support in London and online across the UK.',
    bestFor:
      'Best for senior pets, end-of-life planning, comfort care, quality-of-life reviews and ongoing family support.',
    availability: 'Remote across the UK or home visits in South East London and parts of Kent',
    serviceAreaLabel: 'Remote or home visit',
    ctaLabel: 'Request senior pet support',
    pricingNote: 'Pricing depends on the support required and whether a home visit is needed. Final cost is confirmed after enquiry.',
    hidePublicPricing: true,
  },
  {
    _type: 'service',
    _id: 'service-pet-transport',
    name: 'Pet Transport',
    slug: { _type: 'slug', current: 'pet-transport' },
    shortDescription:
      'Calm, assisted door-to-door transport for small to medium pets who need support getting to appointments or travelling safely.',
    fullDescription: [
      block('pt1', 'Some pets and families need practical help with transport, especially for vet appointments, mobility limitations, relocation or senior care.'),
      block('pt2', 'Soultails offers pet transport support designed to reduce stress and keep the journey as calm and safe as possible.'),
      block('pt3', "Availability depends on distance, timing and your pet's individual needs."),
    ],
    icon: 'Home',
    serviceMode: 'home_visit',
    duration: 'Varies by journey',
    whatToExpect: [
      "Door-to-door transport arranged around your pet's needs",
      'Suitable for small to medium pets on request',
      'Travel planning based on distance, timing and support required',
      'Clear confirmation of cost before the journey is booked',
    ],
    order: 9,
    featured: false,
    metaDescription: 'Pet transport in London and Kent for small to medium pets. Calm, assisted door-to-door support from Soultails.',
    bestFor: 'Best for vet visits, relocation support, senior pets or pets who need calm, assisted door-to-door travel.',
    availability: 'Available on request for small to medium pets in London and Kent',
    serviceAreaLabel: 'Door-to-door transport',
    ctaLabel: 'Ask about pet transport',
    pricingNote: "Pricing is based on distance, timing and your pet's needs. Final cost is confirmed after enquiry.",
    hidePublicPricing: true,
  },
]

export const siteSettings = {
  _type: 'siteSettings',
  _id: 'siteSettings',
  doctorName: 'Dr. Claudia Fioravanti',
  tagline: 'Bringing high quality veterinary care to the comfort of your home',
  bio: [
    block('bio1', "Soultails aims to bring high-quality veterinary care into the comfort of your home, tailored to your pet's individual needs and personality."),
    block('bio2', 'Family members also play an important role in the healing journey, and Soultails aims to guide you towards the best route for your pet\'s long-term wellbeing.'),
    block('bio3', 'The approach combines western veterinary medicine with carefully chosen holistic treatments including acupuncture, osteopathy, herbal medicine and nutritional therapy.'),
    block('bio4', 'Dr. Claudia Fioravanti is a highly qualified veterinary surgeon with advanced certifications in feline behaviour and veterinary practice, serving South East London, parts of Kent and remote clients across the UK.'),
  ],
  credentials: ['DVM', 'MRCVS', 'CertAVP', 'ISFMAdvCerFB'],
  email: 'soultailsinfo@gmail.com',
  serviceArea: 'South East London & parts of Kent',
  quote: 'My goal is to provide every animal with thoughtful, comprehensive care - treating not just the symptoms, but the whole being.',
  aboutValues: [
    { _type: 'object', _key: 'val1', title: 'Integrative approach', desc: 'Combining conventional veterinary medicine with complementary therapies for whole-animal wellbeing.' },
    { _type: 'object', _key: 'val2', title: 'Unhurried consultations', desc: "Every pet deserves time and attention. Your animal's comfort is the priority." },
    { _type: 'object', _key: 'val3', title: 'Evidence-based care', desc: 'Recommendations are grounded in current research and clinical expertise.' },
    { _type: 'object', _key: 'val4', title: 'Compassionate communication', desc: 'Clear, honest guidance that helps families make confident decisions for their pets.' },
  ],
}
